-- ==============================================================================
-- Cuidado+Feliz — Script de Reset e Inicialização Completa no Supabase
-- ==============================================================================

-- 0. Reset (Apaga tabelas antigas para recriar do zero)
DROP TABLE IF EXISTS public.cuidadores CASCADE;
DROP TABLE IF EXISTS public.idosos CASCADE;
DROP TABLE IF EXISTS public.medications CASCADE;
DROP TABLE IF EXISTS public.events CASCADE;
DROP TABLE IF EXISTS public.exercises CASCADE;
DROP TABLE IF EXISTS public.chat_messages CASCADE;

-- 1. Tabela de Cuidadores (Com Hashing de Senha SHA-256 e Código de Vinculação)
CREATE TABLE public.cuidadores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  code TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.cuidadores ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir acesso completo a cuidadores" ON public.cuidadores FOR ALL USING (true) WITH CHECK (true);

-- 2. Tabela de Idosos Cadastrados pelos Cuidadores
CREATE TABLE public.idosos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  caregiver_code TEXT NOT NULL,
  caregiver_name TEXT NOT NULL,
  name TEXT NOT NULL,
  code TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.idosos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir acesso completo a idosos" ON public.idosos FOR ALL USING (true) WITH CHECK (true);

-- 3. Tabela de Medicamentos
CREATE TABLE public.medications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  caregiver_code TEXT,
  idoso_code TEXT,
  idoso_name TEXT,
  name TEXT NOT NULL,
  dosage TEXT DEFAULT 'Dosagem padrão',
  time TEXT NOT NULL,
  instructions TEXT DEFAULT 'Sem instruções adicionais',
  taken BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.medications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir acesso completo a medicamentos" ON public.medications FOR ALL USING (true) WITH CHECK (true);

-- 4. Tabela de Eventos
CREATE TABLE public.events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  date TEXT NOT NULL,
  time TEXT NOT NULL,
  location TEXT NOT NULL,
  category TEXT DEFAULT 'Geral',
  badge TEXT DEFAULT 'Gratuito',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir acesso completo a eventos" ON public.events FOR ALL USING (true) WITH CHECK (true);

-- 5. Tabela de Exercícios
CREATE TABLE public.exercises (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  duration TEXT NOT NULL,
  difficulty TEXT NOT NULL,
  description TEXT NOT NULL
);

ALTER TABLE public.exercises ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir acesso completo a exercícios" ON public.exercises FOR ALL USING (true) WITH CHECK (true);

-- ==============================================================================
-- Dados Iniciais (Seed)
-- ==============================================================================

-- Inserir Cuidador Inicial com hash SHA-256 da senha 'cuidado123' e código 'CF#7X9K'
INSERT INTO public.cuidadores (name, email, password_hash, code) VALUES
  ('Cuidador Demo', 'cuidador@cuidadofeliz.com', '664fb45a1afeedc274ca2cf293191a86a2e33105e75bc48a31f03e471e1da014', 'CF#7X9K');

-- Inserir Idoso Inicial criado pelo Cuidador Demo com código 'ID#9K2P'
INSERT INTO public.idosos (caregiver_code, caregiver_name, name, code) VALUES
  ('CF#7X9K', 'Cuidador Demo', 'Dona Maria da Silva', 'ID#9K2P');

-- Inserir Medicamentos Iniciais vinculados à Dona Maria da Silva
INSERT INTO public.medications (caregiver_code, idoso_code, idoso_name, name, dosage, time, instructions, taken) VALUES
  ('CF#7X9K', 'ID#9K2P', 'Dona Maria da Silva', 'Losartana Potássica', '50 mg', '08:00', 'Tomar com água após o café da manhã', true),
  ('CF#7X9K', 'ID#9K2P', 'Dona Maria da Silva', 'Vitamina D3', '2.000 UI', '12:00', 'Junto com o almoço', false),
  ('CF#7X9K', 'ID#9K2P', 'Dona Maria da Silva', 'Sinvastatina', '20 mg', '20:00', 'Antes de dormir', false);

-- Inserir Eventos Iniciais
INSERT INTO public.events (title, description, date, time, location, category, badge) VALUES
  ('Encontro de Dança e Convivência Senior', 'Uma tarde especial de música leve, dança adaptada e interação social para promover alegria e mobilidade.', '20 de Agosto, 2026', '14:30 às 16:30', 'Centro Comunitário de Apoio ao Idoso', 'Lazer & Social', 'Gratuito'),
  ('Palestra: Saúde da Memória e Bem-Estar', 'Dicas práticas de geriatria e neuropsicologia para exercitar a memória e manter a mente sempre ativa.', '25 de Agosto, 2026', '09:00 às 10:30', 'Auditório da Saúde - Sala 02', 'Saúde & Palestra', 'Vagas Limitadas'),
  ('Oficina Prática de Jardinagem Terapêutica', 'Aprenda técnicas de plantio de ervas medicinais e flores em um ambiente tranquilo ao ar livre.', '28 de Agosto, 2026', '15:00 às 17:00', 'Parque Municipal - Espaço Verde', 'Oficina', 'Gratuito'),
  ('Caminhada Guiada no Parque', 'Caminhada suave acompanhada por educadores físicos e profissionais de enfermagem.', '02 de Setembro, 2026', '08:00 às 09:30', 'Parque Central - Ponto de Encontro 1', 'Atividade Física', 'Gratuito');

-- Inserir Exercícios Iniciais
INSERT INTO public.exercises (title, category, duration, difficulty, description) VALUES
  ('Alongamento Matinal Sentado', 'Alongamento', '10 min', 'Leve', 'Alongamentos suaves para o pescoço, ombros e costas, realizados confortavelmente em uma cadeira.'),
  ('Caminhada Leve e Mobilidade', 'Caminhada', '15 min', 'Moderado', 'Exercícios de marcha no lugar e rotação de tornozelos para melhorar o equilíbrio e a circulação.'),
  ('Fortalecimento de Pernas e Joelhos', 'Fortalecimento', '12 min', 'Leve', 'Movimentos simples de sentar e levantar para preservar a força muscular das pernas.'),
  ('Exercícios de Respiração e Relaxamento', 'Alongamento', '8 min', 'Muito Leve', 'Técnicas de respiração profunda para reduzir a ansiedade e promover o relaxamento corporal.');

-- 6. Tabela de Chat (Mensagens entre Cuidadores e Idosos)
CREATE TABLE public.chat_messages (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  caregiver_code   TEXT NOT NULL,
  idoso_code       TEXT NOT NULL,
  sender_role      TEXT NOT NULL,  -- 'cuidador' | 'idoso'
  sender_name      TEXT NOT NULL,
  content          TEXT NOT NULL,
  created_at       TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir acesso completo a chat" ON public.chat_messages FOR ALL USING (true) WITH CHECK (true);

-- Mensagens de Exemplo (Demo)
INSERT INTO public.chat_messages (caregiver_code, idoso_code, sender_role, sender_name, content) VALUES
  ('CF#7X9K', 'ID#9K2P', 'cuidador', 'Cuidador Demo', 'Bom dia, Dona Maria! Como a senhora está se sentindo hoje?'),
  ('CF#7X9K', 'ID#9K2P', 'idoso',    'Dona Maria da Silva', 'Bom dia! Estou bem, obrigada. Tomei o remédio das 8h.'),
  ('CF#7X9K', 'ID#9K2P', 'cuidador', 'Cuidador Demo', 'Que ótimo! Não esqueça de tomar o da vitamina D no almoço.');

